Add Spring Security and layers for MVC
Vladlis/2017W-D2D3-AZ-Lukyanchikov-Lisetskii pull request #10
Opened 2017-05-04 20:40 UTC by Vladlis

2017-05-04 21:22 UTC, sqshq requested changes

2017-05-04 21:22 UTC, sqshq commented on web-project/src/main/java/com/epam/webproject/service/impl/BookServiceImpl.java
> +@Service("bookService")
Why do we need hardcoded qualifier (here and other places)?

2017-05-04 21:22 UTC, sqshq commented on web-project/src/main/java/com/epam/webproject/dao/impl/BookDaoMock.java
> +    private int id = 0;
It's ok for mock dao, but don't forget that it's not safe to use `HashMap` and `int` for modification in multithreaded environment

2017-05-04 21:22 UTC, sqshq commented on web-project/src/main/java/com/epam/webproject/controller/UserController.java
> +    @RequestMapping("/getAuthor")
I suggest to use REST naming conventions for url path (resources) and http methods to describe the action.

REST naming patterns/antipatterns: http://www.restapitutorial.com/lessons/restfulresourcenaming.html
Must-read about http: https://habrahabr.ru/company/yandex/blog/265569/

2017-05-04 21:22 UTC, sqshq commented on web-project/src/main/java/com/epam/webproject/config/SecurityConfig.java
> +        auth.inMemoryAuthentication()
you can use `.and()` here :)

2017-05-04 21:22 UTC, sqshq commented on web-project/src/main/java/com/epam/webproject/config/SecurityConfig.java
> +                .antMatchers("/admin/**").access("hasRole('ADMIN')")
there is a handy method `.hasRole()` (which is a shortcut for `access("hasRole('...')")` actually

2017-05-23 20:40 UTC, Vladlis commented on web-project/src/main/java/com/epam/webproject/service/impl/BookServiceImpl.java
> +@Service("bookService")
Removed

2017-05-23 20:40 UTC, Vladlis commented on web-project/src/main/java/com/epam/webproject/dao/impl/BookDaoMock.java
> +    private int id = 0;
Fixed

2017-05-23 20:40 UTC, Vladlis commented on web-project/src/main/java/com/epam/webproject/controller/UserController.java
> +    @RequestMapping("/getAuthor")
Done

2017-05-23 20:41 UTC, Vladlis commented on web-project/src/main/java/com/epam/webproject/config/SecurityConfig.java
> +        auth.inMemoryAuthentication()
Fixed

2017-05-23 20:41 UTC, Vladlis commented on web-project/src/main/java/com/epam/webproject/config/SecurityConfig.java
> +                .antMatchers("/admin/**").access("hasRole('ADMIN')")
Done

2017-05-24 16:23 UTC, sqshq approved these changes

2017-05-24 16:24 UTC, merged