Implement REST service with CRUD operations for User
Vladlis/2017W-D2D3-AZ-Lukyanchikov-Lisetskii pull request #6
Opened 2017-03-27 10:59 UTC by Vladlis

2017-03-27 20:17 UTC, alexander-lukyanchikov-epam commented on webservices/rest/src/main/java/com/epam/rest/Application.java
> +@EnableAutoConfiguration
Actually `@SpringBootApplication` [includes both of rest annotations](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/SpringBootApplication.java#L51) :)

2017-03-27 20:22 UTC, alexander-lukyanchikov-epam commented on webservices/rest/src/main/java/com/epam/rest/dao/UserDaoImpl.java
> +    private int counter = 0;
I understand that it is just mock repository implementation, but you know that it is not thread-safe, right? What would be a way to make it safe, with minimum performance impact?

2017-03-27 20:26 UTC, sqshq requested changes

2017-03-27 20:26 UTC, sqshq commented on webservices/rest/src/main/java/com/epam/rest/Application.java
> +@EnableAutoConfiguration
Actually @SpringBootApplication [includes both of rest annotations](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/SpringBootApplication.java#L51) :)

2017-03-27 20:26 UTC, sqshq commented on webservices/rest/src/main/java/com/epam/rest/dao/UserDaoImpl.java
> +    private int counter = 0;
I understand that it is just mock repository implementation, but you know that it is not thread-safe, right? 
What would be a way to make it safe, with minimum performance impact?

2017-03-28 11:56 UTC, Vladlis commented on webservices/rest/src/main/java/com/epam/rest/dao/UserDaoImpl.java
> +    private int counter = 0;
Replaced with AtomicInteger - guess it is the most effective way.

2017-03-28 12:01 UTC, sqshq commented on webservices/rest/src/main/java/com/epam/rest/dao/UserDaoImpl.java
> +    private int counter = 0;
That's right, and there is convenient method `incrementAndGet` for that case.

2017-03-28 12:02 UTC, sqshq commented on webservices/rest/src/main/java/com/epam/rest/dao/UserDaoImpl.java
> +    private int counter = 0;
What about HashMap? Is it thread-safe?

2017-03-28 12:52 UTC, Vladlis commented on webservices/rest/src/main/java/com/epam/rest/dao/UserDaoImpl.java
> +    private int counter = 0;
Nope :)
Replaced with SynchronizedMap.

2017-03-28 12:56 UTC, sqshq commented on webservices/rest/src/main/java/com/epam/rest/dao/UserDaoImpl.java
> +    private int counter = 0;
It is not very efficient way actually. `ConcurrentHashMap` uses sophisticated techniques to reduce the need for synchronization and allow parallel non-blocking read access by multiple threads. `SynchronizedMap` will block threads and degrade performance.

2017-03-28 13:12 UTC, Vladlis commented on webservices/rest/src/main/java/com/epam/rest/dao/UserDaoImpl.java
> +    private int counter = 0;
Thanks, forgot about it.
As I see after a bit of googling it is a matter of a trade-off between consistency and performance. But as you asked about the minimum performance impact, then ConcurrentHashMap is preferable.
Replaced.

2017-03-28 16:35 UTC, sqshq approved these changes

2017-03-28 16:35 UTC, merged